MP-4315 ✨ Webhooks
MyParcelCOM/magento2-plugin pull request #2
Opened 2021-09-02 07:03 UTC by M4tini

https://myparcelcombv.atlassian.net/browse/MP-4315
---
A lot has changed in this PR. I basically changed half the plugin to make it work with a separate `myparcelcom_data` table instead of the old columns added to several Magento core tables. Also a webhook endpoint is added and updating the data in this new table.

2021-09-02 11:44 UTC, zwaans requested changes, later dismissed

2021-09-02 11:44 UTC, zwaans commented on Controller/Adminhtml/Order/CreateMyParcelShipments.php
> -        return $this;
This function no longer needs to return anything?

2021-09-02 11:44 UTC, zwaans commented on Model/Webhook.php
> +            return 1;
these return statements cant be boolean?

2021-09-02 11:44 UTC, zwaans commented on Model/Webhook.php
> +        if (hash_hmac('sha256', json_encode($body), $this->config->getWebhookSecret()) !== $signature) {
Maybe we can check this the other way around, so if something fails in those functions we always throw the error

2021-09-03 08:56 UTC, M4tini commented on Controller/Adminhtml/Order/CreateMyParcelShipments.php
> -        return $this;
I can actually put this stuff in the `execute()` function, I have refactored this in the next PR.

2021-09-03 09:27 UTC, merged